doctrine:
  orm:
    mappings:
      AcMarche\Sepulture:
        is_bundle: false
        dir: '%kernel.project_dir%/src/AcMarche/Sepulture/src/Entity'
        prefix: 'AcMarche\Sepulture'
        alias: AcMarche\Sepulture
    dql:
      string_functions:
        any_value: AcMarche\Sepulture\DoctrineExtensions\AnyValue
