security:
  encoders:
    AcMarche\Sepulture\Entity\User:
      algorithm: auto

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    sepulture_user_provider:
      entity:
        class: AcMarche\Sepulture\Entity\User
        property: email
  firewalls:
    main:
      #anonymous: lazy
      provider: sepulture_user_provider
      custom_authenticator: AcMarche\Sepulture\Security\AppAuthenticator
      logout:
        path: app_logout
  role_hierarchy:
    ROLE_SEPULTURE_ADMIN: [ ROLE_SEPULTURE_EDITEUR ]
