twig:
  form_themes: ['bootstrap_3_layout.html.twig','@FOSCKEditor/Form/ckeditor_widget.html.twig']
  paths:
    '%kernel.project_dir%/src/AcMarche/Sepulture/templates': AcMarcheSepulture
  globals:
    ga_tracking: "%env(GA_TRACKING)%"
    sepulture_ville: "%env(SEPULTURE_VILLE)%"
