vich_uploader:
    mappings:
        patrimoine:
            uri_prefix: /files/patrimoines
            upload_destination: '%kernel.project_dir%/public/files/patrimoines'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
